#!/usr/bin/env python3
"""
Script generated by ChatGPT Free (2026-05-10).
Small changes by me.

Prompt:
"I need a simple command line tool written in Python to copy files and folders.
The tool should do the following:
- inside a starting folder "source" (input parameter),
- search for all files or folders matching a specific string "name" (input parameter),
- copy matching files and folders (with their entire content) to a destination folder "target" (input parameter)

The important thing is to keep the same hierarchy of the copied files/folders in the target folder (parent directories thus need to be copied/created as well).

Please provide a working implementation for this tool, without using any external libraries (only standard Python).
Provide commented code."

A simple command-line tool to:
- Search recursively inside a source folder
- Find files and folders whose name contains a given string
- Copy matching files/folders to a target folder
- Preserve the original directory hierarchy in the target folder

Usage:
python copy_matching.py <source> <name> <target>

Example:
- Copy every file or folder containing "report" in its name into "/backup":
    python copy_matching.py /data/project report /backup
"""

import argparse
import shutil
from pathlib import Path


def copy_match(source_root: Path, item_path: Path, target_root: Path) -> None:
    relative_path = item_path.relative_to(source_root)
    destination = target_root / relative_path

    if item_path.is_dir():
        print(f"[DIR ] Copying: {item_path} -> {destination}")
        shutil.copytree(
            item_path,
            destination,
            dirs_exist_ok=True
        )
    elif item_path.is_file():
        print(f"[FILE] Copying: {item_path} -> {destination}")
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(item_path, destination)


def search_and_copy(source: Path, name: str, target: Path) -> None:
    if not source.exists():
        raise FileNotFoundError(f"Source folder does not exist: {source}")

    if not source.is_dir():
        raise NotADirectoryError(f"Source is not a directory: {source}")

    target.mkdir(parents=True, exist_ok=True)

    matches_found = 0
    for path in source.rglob("*"):
        if name in path.name:
            matches_found += 1
            copy_match(source, path, target)

    print(f"\nDone. {matches_found} matching item(s) copied.")


def main():
    parser = argparse.ArgumentParser(
        description="Copy matching files/folders while preserving hierarchy."
    )

    parser.add_argument(
        "source",
        help="Source folder to search"
    )

    parser.add_argument(
        "name",
        help="String to search for in file/folder names"
    )

    parser.add_argument(
        "target",
        help="Destination folder"
    )

    args = parser.parse_args()

    source = Path(args.source).resolve()
    target = Path(args.target).resolve()

    try:
        search_and_copy(source, args.name, target)
    except Exception as exc:
        print(f"Error: {exc}")


if __name__ == "__main__":
    main()
