"""
Script generated by Gemini AI free (2025-11-20).
Minor changes by me (nothing functional, but styling).

Prompt:
"As a senior Python software developer, write a Python command line script to
scale the size down of images (jpeg) from a folder.
The folder containing the images is provided as an input parameter.
The script takes the images found in the folder 1 by 1, reduce their size by a
specified factor (2 by default, specifiable as parameter) in both width and height,
and then saved them in an output directory (which is also provided as an input parameter).
The script should log its progress while processing, to indicate which image is currently being processed.
The script should also handle multithreading, by parallelizing several conversions at the same time
(maximum number of threads is provided as input parameter to the script).
If you need any more information, ask me before continuing."
Update v2:
"Add the possibility to instead of specifying a scale factor (which should still be possible),
specify a desired output size in pixel for either the big side or the small side,
while keeping the same aspect ratio."

Usage:
python image_scaler.py /path/to/your/input/images /path/to/your/output/folder
Examples:
- Use default parameters (scale factor 2.0, default CPU threads):
    python image_scaler.py ./my_images ./resized_images
- Specify a scale factor of 4.0 and use 8 threads:
    python image_scaler.py /path/to/input /path/to/output --scale_factor 4.0 --max_threads 8
- Specify a target size of 1024 pixels for the longest side:
    python image_scaler_v2.py /path/to/input /path/to/output --target_size 1024 --target_side big

Requires:
- Pillow
"""

import argparse
import logging
import os
from concurrent.futures import ThreadPoolExecutor
from PIL import Image

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    datefmt="%H:%M:%S"
)
logger = logging.getLogger(__name__)

def calculate_new_dimensions(original_width, original_height, scale_factor, target_size, target_side):
    """Calculates the new dimensions based on the chosen method while preserving aspect ratio."""
    if target_size is not None and target_side is not None:
        if target_side == "big":
            if original_width >= original_height:
                new_width = target_size
                new_height = int(original_height * (new_width / original_width))
            else:
                new_height = target_size
                new_width = int(original_width * (new_height / original_height))
        elif target_side == "small":
            if original_width <= original_height:
                new_width = target_size
                new_height = int(original_height * (new_width / original_width))
            else:
                new_height = target_size
                new_width = int(original_width * (new_height / original_height))
    else:
        # default to scale factor method
        new_width = int(original_width / scale_factor)
        new_height = int(original_height / scale_factor)
    
    return max(1, new_width), max(1, new_height)

def resize_image(image_path, output_dir, scale_factor, target_size, target_side):
    """Opens an image, scales it down, and saves it to the output directory."""
    try:
        with Image.open(image_path) as img:
            width, height = img.size

            new_width, new_height = calculate_new_dimensions(
                width, height, scale_factor, target_size, target_side
            )

            # resize the image using an anti-aliasing filter for quality
            # NOTE: Image.Resampling.LANCZOS is preferred over the deprecated Image.ANTIALIAS.
            resized_img = img.resize((new_width, new_height), Image.Resampling.LANCZOS)

            image_name = os.path.basename(image_path)

            output_path = os.path.join(output_dir, image_name)
            os.makedirs(output_dir, exist_ok=True)

            if img.format == "JPEG":
                 resized_img.save(output_path, "JPEG", quality=85, optimize=True)
            else:
                 resized_img.save(output_path)

            logger.info(f"Processed: {image_name} (Original: {width}x{height}, New: {new_width}x{new_height})")

    except Exception as e:
        logger.error(f"Error processing image {image_path}: {e}")

def main():
    """Main function to handle command-line arguments and manage the thread pool."""
    parser = argparse.ArgumentParser(
        description="Scale down images in a folder, either by a factor or target pixel size."
    )

    parser.add_argument("input_folder", type=str, help="Path to the folder containing input images.")
    parser.add_argument("output_folder", type=str, help="Path to the folder where output images will be saved.")
    parser.add_argument(
        "--max_threads",
        type=int,
        default=os.cpu_count() or 4,
        help="Maximum number of threads to use (default: CPU count)."
    )

    group = parser.add_mutually_exclusive_group()
    group.add_argument("--scale_factor",
        type=float,
        default=2.0,
        help="Scale factor to reduce size by (default: 2.0)."
    )
    group.add_argument(
        "--target_size",
        type=int,
        help="Desired output size in pixels for the specified side (e.g., 1024)."
    )

    parser.add_argument(
        "--target_side",
        type=str,
        choices=["big", "small"],
        help="Which side the target_size applies to ('big' or 'small'). Required if --target_size is used."
    )

    args = parser.parse_args()

    if args.target_size is not None and args.target_side is None:
        parser.error("--target_side is required when --target_size is specified.")

    input_dir = args.input_folder
    output_dir = args.output_folder
    scale_factor = args.scale_factor
    target_size = args.target_size
    target_side = args.target_side
    max_threads = args.max_threads

    if not os.path.isdir(input_dir):
        logger.error(f"Input directory not found: {input_dir}")
        return

    image_files = [
        os.path.join(input_dir, f)
        for f in os.listdir(input_dir)
        if f.lower().endswith((".jpg", ".jpeg"))
    ]

    if not image_files:
        logger.info(f"No JPEG images found in {input_dir}.")
        return

    logger.info(f"Found {len(image_files)} images. Starting processing with {max_threads} threads...")

    with ThreadPoolExecutor(max_workers=max_threads) as executor:
        futures = [
            executor.submit(
                resize_image,
                img_path,
                output_dir,
                scale_factor,
                target_size,
                target_side
            )
            for img_path in image_files
        ]
        
        # Optionally, you can use concurrent.futures.as_completed(futures)
        # to process results as they complete, but for this script, simply 
        # submitting them and letting the 'with' statement handle cleanup is enough.

    logger.info("All images processed. Script finished.")


if __name__ == "__main__":
    main()
