"""
Script generated by Gemini AI (2026-02-02).
Small changes by me.

Prompt:
"# Context
I want a small tool developed in Python to filter the content of a text file.
The file is typically a log file composed of a series of lines containing information.
The tool needs to extract specific lines of the file, keeping only relevant ones.
Relevant lines are defined by regular expressions, provided as input to the tool.

# Task
As a Senior Python Tools developer, write a Python script to filter the content of the file.
I want a small command line tool that takes as input the file to filter, and the list of regex
 (provided for example as another text file where each line contains a regex).
The filtered content should be written directly as output text in the execution terminal,
 unless an output text file name is provided as input parameter,
 in which case the filtered content is saved to that file."


Usage:
python log_filter.py "input_file.txt" "regex_file.txt" -o "output_file.txt"

Examples:
- Print filtered lines to terminal:
    python log_filter.py app.log patterns.txt
- Write filtered lines to a file:
    python log_filter.py app.log patterns.txt -o filtered.log
"""

import argparse
import re
import sys
from pathlib import Path
from typing import List


def load_patterns(pattern_file: Path) -> List[re.Pattern]:
    """Load and compile regex patterns from a file."""
    patterns = []

    try:
        with pattern_file.open("r", encoding="utf-8") as f:
            for line_number, line in enumerate(f, start=1):
                line = line.strip()
                if not line:
                    continue
                try:
                    patterns.append(re.compile(line))
                except re.error as e:
                    raise ValueError(
                        f"Invalid regex in '{pattern_file}' "
                        f"(line {line_number}): {e}"
                    )
    except OSError as e:
        raise RuntimeError(f"Failed to read pattern file: {e}")

    if not patterns:
        raise ValueError("No valid regex patterns found.")

    return patterns


def filter_file(
    input_file: Path,
    patterns: List[re.Pattern],
    output_stream
) -> None:
    """Read input file line by line and write matching lines to output stream."""
    try:
        with input_file.open("r", encoding="utf-8", errors="replace") as f:
            for line in f:
                if any(pattern.search(line) for pattern in patterns):
                    output_stream.write(line)
    except OSError as e:
        raise RuntimeError(f"Failed to read input file: {e}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Filter lines of a text file using regex patterns."
    )
    parser.add_argument(
        "input_file",
        type=Path,
        help="Text file to filter (e.g. a log file)"
    )
    parser.add_argument(
        "-p", "--pattern_file",
        type=Path,
        help="File containing regex patterns (one per line)"
    )
    parser.add_argument(
        "-o", "--output",
        type=Path,
        help="Optional output file (defaults to stdout)"
    )

    return parser.parse_args()


def main():
    args = parse_args()

    try:
        patterns = load_patterns(args.pattern_file)

        if args.output:
            with args.output.open("w", encoding="utf-8") as out:
                filter_file(args.input_file, patterns, out)
        else:
            filter_file(args.input_file, patterns, sys.stdout)

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
