"""
Script generated by Gemini AI (2026-01-19).
Small changes by me.

Prompt:
"As a Python tools developer, write a Python script to download all images from the web page at a provided URL, that are contained inside a specific element.
The images relative locations are specified in the "src" attribute of elements of type "img".
Only elements that are indirect children of a main element with a provided "id" must be considered.
All images are saved in a directory on the local machine.

The web page URL, the main element "id", and the output directory are provided as command line parameters."

Update v2 - Image files extensions:
"Add the possibility to specify a list of extensions (image file formats) to filter which images are downloaded. If no file extension is provided, all images are downloaded."


Usage:
python url_img_download.py "https://example.com" "gallery-container" "/path/to/output/folder"

Examples:
- Use default parameters (all image formats):
    python url_img_download.py "https://example.com" "gallery-container" "./images"
- Specify a list of image file formats (JPG + PNG):
    python url_img_download.py "https://example.com" "gallery-container" "./images" --ext jpg png

Requires:
- requests
- bs4
"""

import os
import argparse
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse


def download_images(page_url, element_id, output_dir, extensions=None):
    if extensions:
        extensions = [
            ext.lower() if ext.startswith(".")
            else f".{ext.lower()}"
            for ext in extensions
        ]

    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
        print(f"Created directory: {output_dir}")

    try:
        response = requests.get(page_url)
        response.raise_for_status()
    except requests.exceptions.RequestException as e:
        print(f"Error fetching the URL: {e}")
        return

    soup = BeautifulSoup(response.text, "html.parser")
    main_element = soup.find(id=element_id)

    if not main_element:
        print(f"Element with ID '{element_id}' not found.")
        return

    img_tags = main_element.find_all("img")
    print(f"Found {len(img_tags)} total images inside element '{element_id}'.")

    download_count = 0
    for i, img in enumerate(img_tags):
        src = img.get("src")
        if not src:
            continue

        img_url = urljoin(page_url, src)
        filename = os.path.basename(urlparse(img_url).path)

        if extensions:
            _, ext = os.path.splitext(filename.lower())
            if ext not in extensions:
                continue

        # TODO: remove, should always have name...?
        if not filename:
            filename = f"image_{i}.jpg"

        filepath = os.path.join(output_dir, filename)

        try:
            img_data = requests.get(img_url).content
            with open(filepath, "wb") as f:
                f.write(img_data)
            print(f"Downloaded: {filename}")
            download_count += 1
        except Exception as e:
            print(f"Failed to download {img_url}: {e}")

    print(f"Finished. Downloaded {download_count} images.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Download filtered images from a specific HTML element.")
    parser.add_argument("url", help="URL of the web page")
    parser.add_argument("id", help="ID of the main element containing images")
    parser.add_argument("output", help="Local directory to save images")
    parser.add_argument("--ext", nargs="*", help="List of extensions to filter (e.g., jpg png gif). If omitted, all images are downloaded.")

    args = parser.parse_args()
    download_images(args.url, args.id, args.output, args.ext)
